#!/bin/sh

# Demostration script to initialize the virtual machines system
# EEPROM.

. /etc/machine.conf

if [ x${boot_reason} = "xembed" ]; then
    echo "Initializing ONIE system EEPROM..."
    onie-syseeprom -e
    
    # parse build date
    year=${onie_build_date%%-*}
    rest=${onie_build_date#*-}
    month=${rest%%-*}
    rest=${rest#*-}
    day=${rest%%T*}
    rest=${rest#*T}
    time=${rest%%-*}
    ec2name="$(curl -s  http://169.254.169.254/latest/meta-data/instance-id)" || ec2name="ec2-${RANDOM}"

    onie-syseeprom -s 0x21="ONIE_${onie_machine}_Virtual_Machine"
    onie-syseeprom -s 0x22="vdnos-aws"
    onie-syseeprom -s 0x23="${ec2name}"
    onie-syseeprom -s 0x24=$(onie-sysinfo -e)
    onie-syseeprom -s 0x25="${month}/${day}/${year} ${time}:00"
    onie-syseeprom -s 0x28="$onie_platform"
    onie-syseeprom -s 0x29="$onie_version"
    onie-syseeprom -s 0x2b="DRIVENETS"
    onie-syseeprom -s 0x2c="US"
    onie-syseeprom -s 0x2d="DRIVENETS"
fi
